
spring:
  datasource:
    url: jdbc:mysql://database-1.cj2igaoyci8u.us-east-1.rds.amazonaws.com:3306/transaction_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin1234
  sql:
    init:
      schema-locations: classpath:db/schema-mysql.sql
      data-locations: classpath:db/data-mysql.sql
  redis:
    host: r-wz92pnydc518hrgzfapd.redis.rds.aliyuncs.com
    port: 6379
    password: 3500@game
